server:
  port: 5000
  servlet:
    context-path: /mind-support-service
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: true
spring:
  application:
    name: mind-support-service
  main:
    allow-bean-definition-overriding: true
  jpa:
    open-in-view: true
    hibernate:
      id:
        new_generator_mappings: true
      ddl-auto: update
      naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
chat-gpt:
  model-id: ${MODEL}
  api-key: ${API_KEY}
